name: ☄️​ Icon Update
description: Submit a request for an updated icon.
title: "[Icon Update] "
labels: ["icon update"]
body:
  - type: input
    id: icon-name
    attributes:
      label: Icon Name
      description: What's the icon name?
    validations:
      required: true
  - type: textarea
    id: reference-image
    attributes:
      label: Reference Image (Logo)
      description: Skill logo if available, please share it here.
    validations:
      required: false
  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I have searched for similar requests.
          required: true
        - label: I confirm that I have read and agree to abide by the Code of Conduct.
          required: true